version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12

jobs:
  deploy:
    <<: *defaults  
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
            
workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v*/
            branches:
              only: master
