module.exports = [
  {
    code: 'CMH',
    city: 'Columbus',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    count: 1,
    latitude: 39.998056,
    longitude: -82.891944,
    region: 'North America',
    pricingRegion: 'United States, Mexico, & Canada',
  },
  {
    code: 'HIO',
    city: 'Hillsboro',
    state: 'Oregon',
    country: 'United States',
    countryCode: 'US',
    count: 1,
    latitude: 45.540394,
    longitude: -122.949825,
    region: 'North America',
    pricingRegion: 'United States, Mexico, & Canada',
  },
  {
    code: 'TPA',
    city: 'Tampa',
    state: 'Florida',
    country: 'United States',
    countryCode: 'US',
    count: 1,
    latitude: 27.979722,
    longitude: -82.534722,
    region: 'North America',
    pricingRegion: 'United States, Mexico, & Canada',
  },
  {
    code: 'PNQ',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    count: 1,
    latitude: 18.582222,
    longitude: 73.919722,
    region: 'Asia',
    pricingRegion: 'India',
  },
  {
    code: 'MCT',
    city: 'Muscat',
    state: 'Muscat',
    country: 'Oman',
    countryCode: 'OM',
    count: 1,
    latitude: 23.6015386,
    longitude: 58.2899376,
    region: 'Middle East',
    pricingRegion: 'South Africa, Kenya, & Middle East',
  },
]
